[book]
multilingual = false
src = "src"
title = "Documentation for Mozilla localizers"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/mozilla-l10n/localizer-documentation/"
edit-url-template = "https://github.com/mozilla-l10n/localizer-documentation/edit/main/{path}"
no-section-label = true
